[package]
name = "spacetime-bindings-macro-input-example"
version = "2.10.0"
edition = "2024"
publish = false

[lib]
crate-type = ["cdylib"]

[dependencies]
# https://crates.io/crates/spacetimedb Easy support for interacting between SpacetimeDB and Rust.
spacetimedb = "=2.10.0"
spacetime-bindings-macro-input-example-macros = { version = "=2.10.0", path = "macros" }
